[[inputs.mqtt_consumer]]
  servers = ["tcp://172.30.1.18:1883"]
  topics = ["factory/+/+/+/telemetry"]
  data_format = "json"
  
  # Because we removed json_query, Telegraf can see the whole file and natively tag the ID
  tag_keys = ["device_id"]
  
  # Force one last brand new, uncorrupted database table
  name_override = "factory_pumps_final"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-super-secret-auth-token-12345"
  organization = "my-factory"
  bucket = "telemetry_data"
